Updated aliases for creating shortcuts for each project

diff --git a/alias b/alias
--- a/alias
+++ b/alias
@@ -41,15 +41,55 @@ alias g='grep -i'
 # Install PYENV and .env both
 export PYENV_ROOT="$HOME/.pyenv"
 export PATH="$PYENV_ROOT/bin:$PATH"
-eval "$(pyenv init --path)"
-eval "$(pyenv init -)"
-eval "$(pyenv virtualenv-init -)"
+
 
 ################################################################################
 # Python related aliases
-alias pyver='which python; python --version'
-alias pipver='which pip; pip --version'
+# Function to pretty print Python version and location
+py_info() {
+    python_path=$(which python)
+    python_version=$(python --version 2>&1)
+    echo "Python executable: $python_path"
+    echo "Python version: $python_version"
+    
+    pip_path=$(which pip)
+    pip_version=$(pip --version 2>&1)
+    echo "Pip executable: $pip_path"
+    echo "Pip version: $pip_version"
 
+    if [ -z "$VIRTUAL_ENV" ]; then
+        echo "No virtual environment is currently activated."
+    else
+        echo "Current virtual environment: $VIRTUAL_ENV"
+    fi
+}
+
+# Function to change the prompt to %~>
+change_prompt() {
+    local current_dir=$(basename "$PWD")
+    export PROMPT="($current_dir) %~> "
+}
+
+# All Projects
+go_project() {
+    if [ -z "$1" ]; then
+        echo "Error: No project name provided."
+        return 1
+    fi
+    local project_name="$1"
+    if [ ! -d "$WORK/$project_name" ]; then
+        echo "Error: Project '$project_name' does not exist under $WORK."
+        return 1
+    fi
+    cd "$WORK/$project_name" || return 1
+    if [ -f venv/bin/activate ]; then
+        source venv/bin/activate
+        py_info
+        change_prompt
+    fi
+}
+alias go_eda_schema_internal='goproject eda_schema_internal'
+alias go_ohm='goproject ohm'
 
 ################################################################################
 #
