Added functionality so that run.out is always in the root of the vcode workspace.

diff --git a/alias b/alias
--- a/alias
+++ b/alias
@@ -181,6 +181,15 @@ check_ld_library_path() {   # Display LD_LIBRARY_PATH entries and check for dupl
 setup_graphviz_env() {   # Set up Graphviz environment variables
     [[ ":$PATH:" != *":/usr/local/opt/graphviz/bin:"* ]] && export PATH="/usr/local/opt/graphviz/bin:$PATH"
 }
+
+# -----------------------------------------------------------------------------
+find_vscode_workspace_root() { # Find vscode workspace root directory
+    local dir=$(pwd)
+    while [ "$dir" != "/" ]; do
+        [ -f "$dir/$(basename "$dir").code-workspace" ] && { realpath "$dir"; return; }
+        dir=$(dirname "$dir")
+    done
+}
 # -----------------------------------------------------------------------------
 clean_temp_files() {   # Clean temporary files with feedback
     echo -e "${BLUE}Cleaning temporary files...${RESET}"
@@ -191,6 +200,8 @@ clean_temp_files() {   # Clean temporary files with feedback
 run() {   # Run a Python script with arguments and save output to run.out
     clear
     local script="$1"
+    local ws=$(find_vscode_workspace_root)
+    [ "$ws" ] && output_file="$ws/run.out" || { echo -e "${RED}Error: Workspace directory not set. Exiting.${RESET}"; return 1; }
     local output_file="run.out"
     shift
     [ -z "$script" ] && { echo -e "${RED}Error: No Python script specified.${RESET}"; return 1; }
@@ -207,8 +218,8 @@ run() {   # Run a Python script with arguments and save output to run.out
 run_pytest() {   # Run pytest on specified test files and save output to pytest.out
     clear
     local test_path="$1"
-    local output_file="run.out"
-    shift
+    local ws=$(find_vscode_workspace_root)
+    [ "$ws" ] && output_file="$ws/run.out" || { echo -e "${RED}Error: Workspace directory not set. Exiting.${RESET}"; return 1; }    shift
     
     if [ -z "$test_path" ]; then
         echo -e "${BLUE}Running pytest on current directory with arguments: $*${RESET}"
@@ -231,8 +242,8 @@ run_pytest() {   # Run pytest on specified test files and save output to pytest.
 run_py() {   # Run Python script and save output to run.out
     clear
     local script_path="$1"
-    local output_file="run.out"
-    shift
+    local ws=$(find_vscode_workspace_root)
+    [ "$ws" ] && output_file="$ws/run.out" || { echo -e "${RED}Error: Workspace directory not set. Exiting.${RESET}"; return 1; }    shift
     
     if [ -z "$script_path" ]; then
         echo -e "${RED}Error: No Python script specified.${RESET}"
@@ -255,7 +266,8 @@ run_py() {   # Run Python script and save output to run.out
 run_cmd() {   # Run any shell command and save output to cmd.out
     clear
     local cmd="$1"
-    local output_file="run.out"
+    local ws=$(find_vscode_workspace_root)
+    [ "$ws" ] && output_file="$ws/run.out" ||  output_file="./run.out"
     shift
     [ -z "$cmd" ] && { echo -e "${RED}Error: No command specified.${RESET}"; return 1; }
     echo -e "${BLUE}Running command: $cmd $*${RESET}"
